=== mulesoft-labs/raml-language-server/src/test/example-ramls/exchange/GET_organization_info_200_schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required" : true,
  "type" : "object",
  "properties": {
    "id": { "required": true, "type": "number" },
    "name": { "required": true, "type": "string" },
    "domain": { "required": true, "type": "string" },
    "core_services_id": { "required": true, "type": "string" },
    "objects_amount_limit": { "required": true, "type": "number" },
    "owner_name": { "required": true, "type": "string" },
    "owner_email": { "required": true, "type": "string" },
    "owner_phone": { "required": true, "type": "string" },
    "current_amount": { "required": true, "type": "number" }
  }
}

=== mulesoft-labs/raml-language-server/src/test/example-ramls/exchange/GET_organizations_list_200_example.json
[
  {
    "id": 1,
    "name": "Mulesoft",
    "domain": "",
    "core_services_id": "b2844826-bb5a-4ba1-afdc-3fcb8765e834",
    "owner_name": "Lorem Ipsum",
    "owner_email": "lorem@ipsum.com",
    "owner_phone": "5491177544646"
  },
  {
    "id": 2,
    "name": "Testing",
    "domain": "testing",
    "core_services_id": "",
    "owner_name": "Lorem Ipsum",
    "owner_email": "lorem@ipsum.com",
    "owner_phone": "5491112345678"
  }
]
