=== mulesoft-labs/raml-language-server/src/test/example-ramls/exchange/POST_object_201_schema.json
{
  "type":"object",
  "$schema": "http://json-schema.org/draft-03/schema",
  "id": "http://jsonschema.net",
  "required":false,
  "properties": {
    "name": { "required": true, "type": "string" },
    "summary": { "required": false, "type": ["string","null"] },
    "icon_url": { "required": false, "type": ["string","null"] },
    "owner": { "required": true, "type": "string" },
    "name_url": { "required": true, "type": "string" },
    "type_id": { "required": true, "type": "number" },
    "youtube_video_url": { "required": false, "type": ["string","null"] },
    "video_caption": { "required": false, "type": ["string","null"] },
    "description": { "required":false, "type":["string","null"] },
    "metadata": { "required":false, "type":["array", "null"] },
    "versions": {
      "required":false,
      "type":["array", "null"],
      "properties" : {
        "object_version": { "required": false, "type": "string" },
        "mule_version": { "required": false, "type": "string" },
        "download_url": { "required": false, "type": "string" },
        "doc_url": { "required": false, "type": "string" },
        "feature_id": { "required": false, "type": "string" },
        "api_version": { "required": false, "type": "string" },
        "website": { "required": false, "type": "string" }
      }
    }
  }
}

=== mulesoft-labs/raml-language-server/src/test/example-ramls/exchange/POST_object_201_example.json
{
  "owner":"anypointadmin",
  "type_id":1,
  "versions":[
    {
      "isSuggested":true,
      "object_version":"1.2",
      "mule_version_id":"3.5",
      "download_url":"http://somevalidurl.com",
      "doc_url":"http://anotherValidUrl.com"
    }
  ],
  "name":"Name",
  "name_url":"name-url",
  "icon_url":"http://someurl.com",
  "summary":"summary",
  "youtube_video_url":"http://another.com",
  "video_caption":"some video caption",
  "description":"some description",
  "metadata":[
    {
      "label":"Some label group",
      "type":"tag",
      "values":[
        {
          "text":"Good-tag",
          "value":"Good-tag"
        },
        {
          "text":"Another-tag",
          "value":"Another-tag"
        }
      ]
    }
  ]
}
