=== mulesoft-labs/raml-language-server/src/test/example-ramls/exchange/POST_capacity_increase_schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "properties":{
    "additionalInfo": { "required": true, "type": "string" },
    "contactEmail": { "required": true, "type": "string" },
    "contactPhone": { "required": true, "type": "string" },
    "organization":{
      "required": true,
      "type":"object",
      "properties":{
        "name": { "required": true, "type": "string" },
        "id": { "required": true, "type": "string" },
        "createdAt": { "required": true, "type": "string" },
        "ownerId": { "required": true, "type": "string" },
        "updatedAt": { "required": true, "type": "string" },
        "clientId": { "required": true, "type": "string" },
        "domain": { "required": true, "type": "string" },
        "idprovider_id": { "required": true, "type": "string" }
      }
    }
  }
}

=== mulesoft-labs/raml-language-server/src/test/example-ramls/exchange/POST_capacity_increase_example.json
{
  "additionalInfo": "HeyHo",
  "contactEmail": "hola@pianola.com",
  "contactPhone": "45631209",
  "organization": {
      "name": "Mulesoft",
      "id": "b2844826-bb5a-4ba1-afdc-3fcb8765e834",
      "createdAt": "2015-01-08T21:40:39.605Z",
      "ownerId": "462ddd98-edd2-423b-9218-9f8e0f4c42ba",
      "updatedAt": "2015-01-08T21:40:39.656Z",
      "clientId": "32c8a763bc494a3eabf70849aad246e6",
      "domain": "mulesoft",
      "idprovider_id": "mulesoft"
  }
}
