=== mulesoft-labs/raml-language-server/src/test/example-ramls/exchange/PUT_object_204_schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "properties": {
    "name": { "required": true, "type": "string" },
    "summary": { "required": false, "type": ["string","null"] },
    "icon_url": { "required": false, "type": ["string","null"] },
    "youtube_video_url": { "required": false, "type": ["string","null"] },
    "video_caption": { "required": false, "type": ["string","null"] },
    "description": { "required":false, "type":["string","null"] },
    "metadata": { "required":false, "type":["array", "null"] },
    "versions": {
      "required":false,
      "type":["array", "null"],
      "properties" : {
        "object_version": { "required": false, "type": "string" },
        "mule_version": { "required": false, "type": "string" },
        "download_url": { "required": false, "type": "string" },
        "doc_url": { "required": false, "type": "string" },
        "feature_id": { "required": false, "type": "string" },
        "api_version": { "required": false, "type": "string" },
        "website": { "required": false, "type": "string" }
      }
    }
  }
}

=== mulesoft-labs/raml-language-server/src/test/example-ramls/exchange/PUT_object_204_example.json
{
  "name":"Name",
  "summary":"summary",
  "description":"some description",
  "video_caption":"some video caption",
  "icon_url":"http://someurl.com",
  "youtube_video_url":"http://another.com",
  "metadata":[
    {
      "id":19356,
      "object_id":273,
      "label":"Some label group",
      "type":"tag",
      "text":"Good-tag",
      "value":"Good-tag"
    },
    {
      "id":19357,
      "object_id":273,
      "label":"Some label group",
      "type":"tag",
      "text":"Another-tag",
      "value":"Another-tag"
    }
  ],
  "versions":[
    {
      "id":874,
      "object_id":273,
      "mule_version_id":"3.5",
      "download_url":"http://somevalidurl.com",
      "doc_url":"http://anotherValidUrl.com",
      "feature_id":null,
      "object_version":"1.2",
      "api_version":null,
      "website":null,
      "muleVersion":{
        "id":"3.5",
        "connectors_update_site_url":"http://repository.mulesoft.org/connectors/releases/3.5.0",
        "doc_url":"http://www.mulesoft.org/documentation/display/current/Home",
        "feature_id":null,
        "active":true
      },
      "actions":[
        {
          "type":"download"
        }
      ],
      "isSuggested":true
    }
  ]
}
